# Generated by Django 3.0.5 on 2020-04-05 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('p_id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Patient ID')),
                ('fname', models.CharField(max_length=255, verbose_name='Firstname')),
                ('lname', models.CharField(max_length=255, verbose_name='Lastname')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('birth_day', models.DateField(verbose_name='Birth date')),
                ('status', models.CharField(choices=[('S', 'Single'), ('M', 'Married')], max_length=1, verbose_name='Patient Condition')),
                ('blood_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB')], max_length=2, verbose_name='Patient Condition')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('address', models.TextField(verbose_name='Address')),
                ('date', models.DateField(auto_now=True, verbose_name='Created Date')),
                ('public_health_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='User_app.Public_Health', verbose_name='Creator ID')),
            ],
        ),
        migrations.CreateModel(
            name='Congenital_disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Congenital disease name')),
                ('patient_id', models.ManyToManyField(to='User_app.Patient', verbose_name='Patient ID')),
            ],
        ),
    ]
