# Generated by Django 3.0.5 on 2020-04-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_role',
            field=models.CharField(choices=[('1', 'Student'), ('2', 'Staff'), ('3', 'KOSEN'), ('4', 'KMIDS'), ('5', 'CMKL')], default='1', max_length=2, verbose_name='Patient Role'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB')], max_length=2, verbose_name='Blood Type'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('O', 'Others')], max_length=1, verbose_name='Patient Condition'),
        ),
    ]
