# Generated by Django 3.0.5 on 2020-04-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodyache_diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodyache_area', models.CharField(max_length=255, verbose_name='Symptom detail')),
                ('bodyache_date', models.IntegerField(verbose_name='How long ? (day)')),
                ('pain_score', models.IntegerField(verbose_name='Pain score')),
                ('ache_detail', models.CharField(max_length=255, verbose_name='Ache detail')),
                ('trigger', models.CharField(max_length=255, verbose_name='Stimulus/Relief')),
                ('crack', models.CharField(max_length=255, verbose_name='Crack')),
                ('others', models.CharField(max_length=255, verbose_name='Other symtoms')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_detail', models.CharField(max_length=255, verbose_name='Diagnosis detail')),
            ],
        ),
        migrations.CreateModel(
            name='Diarrhea_diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diarrhea_detail', models.CharField(max_length=255, verbose_name='Diarrhea detail')),
                ('stomachache', models.CharField(max_length=255, verbose_name='Stomachache')),
                ('vomit', models.BooleanField(verbose_name='Squeamish / Vomit')),
                ('flux_stool', models.BooleanField(verbose_name='Flux stool')),
                ('fever', models.BooleanField(verbose_name='Fever')),
                ('symptom_detail', models.CharField(max_length=255, verbose_name='Symptom detail')),
            ],
        ),
        migrations.CreateModel(
            name='Eye_diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.BooleanField(verbose_name='Left')),
                ('right', models.BooleanField(verbose_name='Right')),
                ('pain', models.BooleanField(verbose_name='Pain')),
                ('irritation', models.BooleanField(verbose_name='Irritation')),
                ('itch', models.BooleanField(verbose_name='Itch')),
                ('conjunctivitis', models.BooleanField(verbose_name='Conjunctivitis')),
                ('sore', models.BooleanField(verbose_name='Sore Eyelids')),
                ('swoll', models.BooleanField(verbose_name='Swollen Eyelids')),
                ('tear', models.BooleanField(verbose_name='Teary')),
                ('blurred', models.BooleanField(verbose_name='Blurred Vision')),
                ('gum', models.BooleanField(verbose_name='Gum in the eye')),
                ('purulent', models.BooleanField(verbose_name='Purulent eye')),
                ('matter', models.BooleanField(verbose_name='Foreign matter into the eye')),
                ('check_up', models.CharField(max_length=255, verbose_name='Check up')),
            ],
        ),
        migrations.CreateModel(
            name='Fever_diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fever', models.BooleanField(verbose_name='Fever')),
                ('cough', models.BooleanField(verbose_name='Cough')),
                ('phlegm', models.BooleanField(verbose_name='Phlegm')),
                ('snot', models.BooleanField(verbose_name='Snot')),
                ('headache', models.BooleanField(verbose_name='Headache')),
                ('stuffy', models.BooleanField(verbose_name='Stuffy Nose')),
                ('food_bored', models.BooleanField(verbose_name='Bored with food')),
                ('body_aches', models.BooleanField(verbose_name='Body aches')),
                ('sore_throat', models.BooleanField(verbose_name='Sore throat')),
                ('eye_itch', models.BooleanField(verbose_name='Eye itching')),
                ('injected_pharynx', models.BooleanField(verbose_name='Injected pharynx')),
                ('exudates', models.BooleanField(verbose_name='Exudates')),
                ('lungs', models.BooleanField(verbose_name='Lungs : Clear')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255, verbose_name='Prescription detail')),
            ],
        ),
        migrations.CreateModel(
            name='Rash_diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rash_area', models.CharField(max_length=255, verbose_name='Rash Area')),
                ('rash_date', models.IntegerField(verbose_name='How long ? (day)')),
                ('itch', models.BooleanField(verbose_name='Itch')),
                ('pain', models.BooleanField(verbose_name='Pain')),
                ('sting', models.BooleanField(verbose_name='Sting')),
                ('fever', models.BooleanField(verbose_name='Fever')),
                ('swell', models.BooleanField(verbose_name='Swell')),
                ('rash_detail', models.CharField(max_length=255, verbose_name='Rash Detail')),
                ('pe', models.CharField(max_length=255, verbose_name='PE')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Symtom name')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('cn', models.IntegerField(primary_key=True, serialize=False, verbose_name='Clinic number')),
                ('weight', models.FloatField(verbose_name='Weight')),
                ('Height', models.FloatField(verbose_name='Height')),
                ('bp', models.IntegerField(verbose_name='Blood pressures')),
                ('pr', models.IntegerField(verbose_name='Pulse rates')),
                ('temp', models.FloatField(verbose_name='Temperatures')),
                ('rr', models.IntegerField(verbose_name='Respiratory rates')),
                ('bmi', models.FloatField(verbose_name='BMI')),
                ('o2_sat', models.IntegerField(verbose_name='Oxygen saturation')),
                ('med_cer', models.BooleanField(verbose_name='Medical certificate')),
                ('follow_up', models.DateField(verbose_name='Follow up ?')),
                ('patient_condition', models.CharField(choices=[('SC', 'Selfcome'), ('AB', 'Ambulance'), ('ST', 'Stretcher')], max_length=2, verbose_name='Patient Condition')),
                ('current_history', models.CharField(max_length=255, verbose_name='Current History')),
                ('date', models.DateField(auto_now=True, verbose_name='')),
                ('important_symptom', models.CharField(max_length=255, verbose_name='Important Symptom')),
                ('detail', models.CharField(max_length=255, verbose_name='Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Wound_diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helmet', models.BooleanField(verbose_name='Is helmet on ?')),
                ('seatbelt', models.BooleanField(verbose_name='Is seatbelt on ?')),
                ('wound_detail', models.CharField(max_length=255, verbose_name='Wound Detail')),
                ('wound_type', models.CharField(choices=[('1', 'Scratched'), ('2', 'Tear'), ('3', 'From Sharp object'), ('4', 'Others')], max_length=1, verbose_name='Rash Type')),
                ('wound_area', models.CharField(max_length=255, verbose_name='Wound Area')),
                ('wound_size', models.CharField(max_length=255, verbose_name='Wound Size')),
                ('wound_date', models.DateField(verbose_name='Date of accident')),
                ('wound_locale', models.CharField(max_length=255, verbose_name='Locale of accident')),
                ('treatment_before', models.CharField(choices=[('N', 'Never had treatment before'), ('Y', 'Had treatment before')], max_length=1, verbose_name='Had treatment before ?')),
                ('treatment_before_detail', models.CharField(max_length=255, verbose_name='Last treatment detail')),
                ('doctor_fee', models.IntegerField(verbose_name='Doctor fee')),
                ('diagnosis_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Treatment.Diagnosis', verbose_name='Diagnosis ID')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment_method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255, verbose_name='Treatment method detail')),
                ('symptom_detail_id', models.ManyToManyField(to='Treatment.Symptom_detail', verbose_name='Symptom Detail ID')),
            ],
        ),
    ]
