# Generated by Django 3.0.5 on 2020-04-05 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User_app', '0002_congenital_disease_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Symtom name')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Treatment.Symptom', verbose_name='Symptom ID')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment_method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255, verbose_name='Treatment method detail')),
                ('symptom_detail_id', models.ManyToManyField(to='Treatment.Symptom_detail', verbose_name='Symptom Detail ID')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('cn', models.IntegerField(primary_key=True, serialize=False, verbose_name='Clinic number')),
                ('weight', models.FloatField(verbose_name='Weight')),
                ('Height', models.FloatField(verbose_name='Height')),
                ('bp', models.IntegerField(verbose_name='Blood pressures')),
                ('pr', models.IntegerField(verbose_name='Pulse rates')),
                ('temp', models.FloatField(verbose_name='Temperatures')),
                ('rr', models.IntegerField(verbose_name='Respiratory rates')),
                ('bmi', models.FloatField(verbose_name='BMI')),
                ('o2_sat', models.IntegerField(verbose_name='Oxygen saturation')),
                ('med_cer', models.BooleanField(verbose_name='Medical certificate')),
                ('follow_up', models.DateField(verbose_name='Follow up ?')),
                ('patient_condition', models.CharField(choices=[('SC', 'Selfcome'), ('AB', 'Ambulance'), ('ST', 'Stretcher')], max_length=2, verbose_name='Patient Condition')),
                ('current_history', models.CharField(max_length=255, verbose_name='Current History')),
                ('date', models.DateField(auto_now=True, verbose_name='')),
                ('important_symptom', models.CharField(max_length=255, verbose_name='Important Symptom')),
                ('detail', models.CharField(max_length=255, verbose_name='Detail')),
                ('patient_p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_app.Patient', verbose_name='Patient ID')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator user')),
            ],
        ),
        migrations.AddField(
            model_name='symptom_detail',
            name='treatment_cn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Treatment.Treatment', verbose_name='Treatment Clinic number'),
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_detail', models.CharField(max_length=255, verbose_name='Diagnosis detail')),
                ('symptom_detail_id', models.ManyToManyField(to='Treatment.Symptom_detail', verbose_name='Symptom Detail ID')),
            ],
        ),
    ]
