# Generated by Django 3.0.5 on 2020-04-16 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Treatment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='patient_p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_app.Patient', verbose_name='Patient ID'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator user'),
        ),
        migrations.AddField(
            model_name='symptom_detail',
            name='symptom_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Treatment.Symptom', verbose_name='Symptom ID'),
        ),
        migrations.AddField(
            model_name='symptom_detail',
            name='treatment_cn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Treatment.Treatment', verbose_name='Treatment Clinic number'),
        ),
        migrations.AddField(
            model_name='rash_diagnosis',
            name='diagnosis_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Treatment.Diagnosis', verbose_name='Diagnosis ID'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='nurse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_app.Nurse', verbose_name='Creator ID'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='treatment_cn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Treatment.Treatment', verbose_name='Treatment Clinic number'),
        ),
        migrations.AddField(
            model_name='fever_diagnosis',
            name='diagnosis_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Treatment.Diagnosis', verbose_name='Diagnosis ID'),
        ),
        migrations.AddField(
            model_name='eye_diagnosis',
            name='diagnosis_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Treatment.Diagnosis', verbose_name='Diagnosis ID'),
        ),
        migrations.AddField(
            model_name='diarrhea_diagnosis',
            name='diagnosis_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Treatment.Diagnosis', verbose_name='Diagnosis ID'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='symptom_detail_id',
            field=models.ManyToManyField(to='Treatment.Symptom_detail', verbose_name='Symptom Detail ID'),
        ),
        migrations.AddField(
            model_name='bodyache_diagnosis',
            name='diagnosis_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Treatment.Diagnosis', verbose_name='Diagnosis ID'),
        ),
    ]
