# Generated by Django 3.0.5 on 2020-04-05 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0002_congenital_disease_patient'),
        ('Treatment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255, verbose_name='Prescription detail')),
                ('nurse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_app.Nurse', verbose_name='Creator ID')),
                ('treatment_cn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Treatment.Treatment', verbose_name='Treatment Clinic number')),
            ],
        ),
    ]
