# Generated by Django 3.0.5 on 2020-04-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('type', models.CharField(choices=[('D', 'dis_drug'), ('M', 'dis_med')], max_length=1, verbose_name='Dispense type')),
            ],
        ),
        migrations.CreateModel(
            name='Med_supply',
            fields=[
                ('med_sup_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Medical supply ID')),
                ('name', models.CharField(max_length=255, verbose_name='Medical supply name')),
                ('amount', models.IntegerField(verbose_name='Amount left')),
                ('dis_med_id', models.ManyToManyField(to='Medicine.Dispense', verbose_name='Dispense ID')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('med_sup_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Drug ID')),
                ('name', models.CharField(max_length=255, verbose_name='Drug name')),
                ('amount', models.IntegerField(verbose_name='Amount left')),
                ('dis_med_id', models.ManyToManyField(to='Medicine.Dispense', verbose_name='Dispense ID')),
            ],
        ),
    ]
