# Generated by Django 3.0.5 on 2020-04-05 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User_app', '0002_congenital_disease_patient'),
        ('Treatment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('type', models.CharField(choices=[('D', 'dis_drug'), ('M', 'dis_med')], max_length=1, verbose_name='Dispense type')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255, verbose_name='Prescription detail')),
                ('nurse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_app.Nurse', verbose_name='Creator ID')),
                ('treatment_cn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Treatment.Treatment', verbose_name='Treatment Clinic number')),
            ],
        ),
        migrations.CreateModel(
            name='Med_supply',
            fields=[
                ('med_sup_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Medical supply ID')),
                ('name', models.CharField(max_length=255, verbose_name='Medical supply name')),
                ('amount', models.IntegerField(verbose_name='Amount left')),
                ('dis_med_id', models.ManyToManyField(to='Medicine.Dispense', verbose_name='Dispense ID')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('med_sup_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Drug ID')),
                ('name', models.CharField(max_length=255, verbose_name='Drug name')),
                ('amount', models.IntegerField(verbose_name='Amount left')),
                ('dis_med_id', models.ManyToManyField(to='Medicine.Dispense', verbose_name='Dispense ID')),
            ],
        ),
        migrations.AddField(
            model_name='dispense',
            name='prescription_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medicine.Prescription', verbose_name='Prescription ID'),
        ),
    ]
