# Generated by Django 3.0.5 on 2020-04-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medicine', '0001_initial'),
        ('User_app', '0001_initial'),
        ('Treatment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='patient',
            field=models.ManyToManyField(to='User_app.Patient', verbose_name='Allergic Drug(s)'),
        ),
        migrations.AddField(
            model_name='dispense',
            name='prescription_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Treatment.Prescription', verbose_name='Prescription ID'),
        ),
    ]
