# Generated by Django 3.0.5 on 2020-04-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0002_congenital_disease_patient'),
        ('Medicine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='nurse_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='treatment_cn',
        ),
        migrations.AddField(
            model_name='drug',
            name='patient',
            field=models.ManyToManyField(to='User_app.Patient', verbose_name='Allergic Drug(s)'),
        ),
    ]
