# Generated by Django 3.0.5 on 2020-04-05 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0002_auto_20200405_2155'),
        ('Treatment', '0002_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispense',
            name='prescription_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Treatment.Prescription', verbose_name='Prescription ID'),
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
